version: "3.4"

services:
  api:
    image: airlinebookingwithfastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    command:
      ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
    volumes:
      - .:/app
