version: "3.4"

services:
  api:
    image: airline-booking-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    depends_on:
      - db
    command:
      ["sh", "-c", "uvicorn main:app --reload --host 0.0.0.0 --port 8000"]
    ports:
      - 8000:8000
    volumes:
      - .:/app
    develop:
      watch:
        - path: ./requirements.txt
          action: rebuild
        - path: /app
          action: sync

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data-db:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: airline_booking

volumes:
  db-data:
